export const REGISTER_STORE = "REGISTER_STORE";

export const SET_STORE_ERROR = "SET_STORE_ERROR";

export const SET_SLOTS = "SET_SLOTS";

export const ADD_STORE_OWNER = "ADD_STORE_OWNER";

export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";

export const AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE";

export const SET_STORE = "SET_STORE";

export const FETCH_CATEGORIES = "FETCH_CATEGORIES";

export const SET_CATEGORIES = "SET_CATEGORIES";

export const LOG_IN_USER = "LOG_IN_USER";

export const SET_INACTIVE_SLOTS = "SET_INACTIVE_SLOTS";

export const FETCH_STORES = "FETCH_STORES";

export const SET_STORES = "SET_STORES";

export const GET_STORE_DETAILS = "GET_STORE_DETAILS";

export const FETCH_ADMIN_STORES = "FETCH_ADMIN_STORES";

export const DISABLE_STORE = "DISABLE_STORE";
